// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrVRiYcq5CCXE3o-J-a9gVH5jaUu8CTBI',
    appId: '1:786114937390:web:35722e39a752944d5595bf',
    messagingSenderId: '786114937390',
    projectId: 'notemates-c906b',
    authDomain: 'notemates-c906b.firebaseapp.com',
    storageBucket: 'notemates-c906b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxqmn6wlzlu8Gludyg_4xefek1w94rAls',
    appId: '1:786114937390:android:b5ece38a98b2e7375595bf',
    messagingSenderId: '786114937390',
    projectId: 'notemates-c906b',
    storageBucket: 'notemates-c906b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBUQXYJx2AXRl51GmI6b4Rmp5CdukqtZo',
    appId: '1:786114937390:ios:aa269ad724be49945595bf',
    messagingSenderId: '786114937390',
    projectId: 'notemates-c906b',
    storageBucket: 'notemates-c906b.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBUQXYJx2AXRl51GmI6b4Rmp5CdukqtZo',
    appId: '1:786114937390:ios:aa269ad724be49945595bf',
    messagingSenderId: '786114937390',
    projectId: 'notemates-c906b',
    storageBucket: 'notemates-c906b.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrVRiYcq5CCXE3o-J-a9gVH5jaUu8CTBI',
    appId: '1:786114937390:web:34c41155f4c5bc125595bf',
    messagingSenderId: '786114937390',
    projectId: 'notemates-c906b',
    authDomain: 'notemates-c906b.firebaseapp.com',
    storageBucket: 'notemates-c906b.firebasestorage.app',
  );

}